### PR TITLE
changed setInterval to asetTimeout method

### PR DESCRIPTION
**Pull request by Salandora**
Refactored the setInterval to setTimeout.
Changed on the FPS will directly take effect now.

### CODE REVIEW

**Comment by markwal** [comment]
I don't think we want timeout do we?

The line should be needed because the code intends to avoid setting the interval if the src is empty.  This is so that when you switch away from the tab, foosel's code sets the src to empty and we don't want to just set it back again we want to clear our timer.

**Comment by markwal** [comment]
http://stackoverflow.com/questions/2696692/setinterval-vs-settimeout

**Comment by Salandora** [comment]
Atleast with timeout you can dynamically change the FPS without the need to refresh the page.

With the Line you'Re right my fault hadn't seen it correctly.

**Comment by markwal** [comment]
Merged 6f0e647

**Pull request closed without merging**
